<a href="https://colab.research.google.com/github/yohanesnuwara/LiDAR/blob/main/TRV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns 
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler

%config InlineBackend.figure_format='retina'

In [2]:
path = '/content/Correlated_LiDAR_PAT_220_Plots.csv'

df = pd.read_csv(path)

df

,Plot,MaxCHT,MeanCHT,q25CHT,q50CHT,q75CHT,HTmaxLDens,AllReturn,Return1,Return2,...,Dq (cm),Dq Planted (cm),MDD (cm),MinD (cm),MaxD (cm),VarD,BA (m2/ha),TSV (m3 sub),TRV (m3 sub),MAI (m3 sub/ha/a)
0,A020T27A,19.337,12.508353,10.6320,13.6770,15.616,13.5,276764.391,247302.641,28749.738,...,11.3,11.3,19.3,6.4,21.8,13.6,16.6,122.6,109.2,36.6
1,A021T9A,17.617,10.532304,8.2370,11.2140,13.734,13.5,246277.763,218492.646,27207.259,...,11.9,11.9,19.7,6.3,20.8,20.8,13.3,93.9,83.9,28.2
2,A022T6A,18.134,12.027277,10.8095,13.2470,14.793,1.5,444625.410,380001.819,62145.088,...,11.8,11.8,18.8,6.0,19.6,11.3,21.0,163.1,147.0,49.3
3,A023T16A,16.831,11.103857,9.0840,11.3560,13.621,1.5,327667.518,239965.448,79140.610,...,11.2,11.2,20.0,6.0,22.6,15.2,16.4,119.1,104.8,35.3
4,A024T3A,19.576,11.150196,9.0000,11.4190,13.969,1.5,1456786.804,1133941.481,297600.831,...,12.1,12.1,18.3,6.2,19.7,12.9,16.9,117.5,106.5,35.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,E293T10A,22.012,14.271730,15.1130,17.2170,18.607,1.5,555020.591,514652.873,39801.988,...,14.3,14.3,16.4,8.7,17.1,2.8,16.6,129.4,120.7,40.1
216,E294T13A,21.449,13.196528,10.7485,16.6160,17.858,1.5,362856.092,346949.912,15628.559,...,12.5,12.5,14.6,5.4,14.9,4.3,16.6,115.7,104.2,35.5
217,E295T8B,18.841,12.123137,10.6040,15.4330,16.670,16.5,340382.587,326366.972,13936.463,...,11.5,11.5,13.2,5.9,13.4,2.5,12.0,85.8,75.4,25.4
218,E296T21A,20.386,13.219501,9.7865,16.8950,17.980,1.5,487923.964,454578.994,32756.536,...,12.6,12.6,14.4,8.2,14.5,2.1,14.3,108.9,98.7,32.8
219,E297T17A,24.384,11.723853,0.3990,16.4925,20.096,1.5,385493.596,360109.883,24822.869,...,11.7,11.7,14.2,7.7,14.5,2.5,12.9,108.6,96.7,32.5

In [3]:
df_epel = df[df.Species=='EPEL']

df_epel

,Plot,MaxCHT,MeanCHT,q25CHT,q50CHT,q75CHT,HTmaxLDens,AllReturn,Return1,Return2,...,Dq (cm),Dq Planted (cm),MDD (cm),MinD (cm),MaxD (cm),VarD,BA (m2/ha),TSV (m3 sub),TRV (m3 sub),MAI (m3 sub/ha/a)
70,E063T1A,19.968,13.740243,14.52275,15.8670,16.853,1.5,535391.078,477390.990,54234.390,...,11.4,11.4,14.5,6.2,15.2,4.4,13.1,89.2,77.4,26.4
71,E064T1A,19.548,11.984318,8.87900,14.5240,16.132,1.5,567129.556,514187.180,49928.549,...,12.1,12.1,15.7,6.6,16.4,7.6,12.4,89.7,79.3,26.4
72,E065T1B,15.436,6.895030,0.47700,8.2560,11.581,1.5,266269.764,237733.745,27164.688,...,12.2,12.2,13.4,6.2,14.2,2.1,7.8,46.0,37.9,12.8
73,E066T6A,17.677,10.461244,5.14500,13.3870,14.963,1.5,408328.522,373393.188,33704.585,...,13.1,13.1,14.5,9.0,16.6,1.9,11.9,78.2,71.5,23.6
74,E067T1A,19.204,12.192320,9.69025,13.8970,15.995,1.5,589483.124,511614.147,71049.645,...,11.2,11.2,14.8,6.1,16.1,6.0,11.7,76.7,66.2,22.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,E293T10A,22.012,14.271730,15.11300,17.2170,18.607,1.5,555020.591,514652.873,39801.988,...,14.3,14.3,16.4,8.7,17.1,2.8,16.6,129.4,120.7,40.1
216,E294T13A,21.449,13.196528,10.74850,16.6160,17.858,1.5,362856.092,346949.912,15628.559,...,12.5,12.5,14.6,5.4,14.9,4.3,16.6,115.7,104.2,35.5
217,E295T8B,18.841,12.123137,10.60400,15.4330,16.670,16.5,340382.587,326366.972,13936.463,...,11.5,11.5,13.2,5.9,13.4,2.5,12.0,85.8,75.4,25.4
218,E296T21A,20.386,13.219501,9.78650,16.8950,17.980,1.5,487923.964,454578.994,32756.536,...,12.6,12.6,14.4,8.2,14.5,2.1,14.3,108.9,98.7,32.8
219,E297T17A,24.384,11.723853,0.39900,16.4925,20.096,1.5,385493.596,360109.883,24822.869,...,11.7,11.7,14.2,7.7,14.5,2.5,12.9,108.6,96.7,32.5

In [4]:
# feature_interest = ['hq85', 'q75CHT', 'hvar', 'hq95', 'hq75', 
#                     'hsd', 'MaxCHT', 'hmax', 'hq65', 'SVol', 
#                     'q50CHT', 'hmean', 'MeanCHT', 'Imax', 'rugosity', 
#                     'canopy.area', 'GRVI', 'rumple', 'MGRVI'] # VARI has inf

feature_interest = ['Plot', 'KeyID',
                    'hq85', 'q75CHT', 'hvar', 'hq95', 'hq75', 
                    'hsd', 'MaxCHT', 'hmax', 'hq65', 'SVol'] # VARI has inf

target_interest = 'TRV (m3 sub)' 

X = df_epel[feature_interest]
y = df_epel[target_interest]

df_interest = pd.concat((X,y), axis=1)

df_interest

,Plot,KeyID,hq85,q75CHT,hvar,hq95,hq75,hsd,MaxCHT,hmax,hq65,SVol,TRV (m3 sub)
70,E063T1A,GLBC019705,16.82300,16.853,58.02,18.1280,16.14600,7.62,19.968,19.97,15.56200,13519.838,77.4
71,E064T1A,GLBC019901,16.33000,16.132,48.69,17.5410,15.39925,6.98,19.548,19.55,14.34500,11632.046,79.3
72,E065T1B,GLBC020002,11.81675,11.581,26.63,13.3480,10.41500,5.16,15.436,15.44,8.34175,6944.190,37.9
73,E066T6A,GLBC020004,15.09300,14.963,44.81,16.0839,14.28800,6.69,17.677,17.68,13.34200,10543.639,71.5
74,E067T1A,GLBC020102,16.00080,15.995,43.03,17.1240,14.78400,6.56,19.204,19.20,13.21520,11596.003,66.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,E293T10A,TPGE101A01,18.89100,18.607,70.56,19.9400,18.14500,8.40,22.012,22.01,17.41600,13561.266,120.7
216,E294T13A,TPGE146A01,18.04585,17.858,66.99,18.9080,17.37600,8.19,21.449,21.45,16.72900,13171.349,104.2
217,E295T8B,TPGE146A02,16.99370,16.670,58.69,17.6970,16.32550,7.66,18.841,18.84,15.72600,11562.205,75.4
218,E296T21A,TPGE147A01,18.16000,17.980,69.65,18.9240,17.55500,8.35,20.386,20.39,16.99015,12444.173,98.7
219,E297T17A,TPGE147A02,20.61000,20.096,87.30,22.2950,19.17075,9.34,24.384,24.38,17.36365,11261.979,96.7

In [5]:
# import plotly.express as px

# columns = ['Plot', 'KeyID',
#                     'hq85', 'q75CHT', 'hvar', 'hq95', 'hq75', 
#                     'hsd', 'MaxCHT', 'hmax', 'hq65', 'SVol', 'TRV (m3 sub)']

# fig = px.scatter_matrix(df_interest, dimensions=columns[2:], hover_data=['Plot', 'KeyID'],
#                         height=1000, width=1000, title="Scatter Plot Matrix")
# fig.update_traces(showupperhalf=False, diagonal_visible=False)
# fig.show()

In [13]:
plot_outlier = ['E276T1A', 'E148T18A', 'E065T1B', 'E297T17A', 'E204T1A', 'E105T1A',
                'E079T15A', 'E225T1A', 'E118T23A', 'E128T19A', 'E289T16A','E260T16A', 'E111T14A',
                'E241T21A', 'E244T22A', 'E237T10A', 'E094T6A']
df_outlier_remove = df_interest[~df_interest.Plot.isin(plot_outlier)]

df_outlier_remove

# fig = px.scatter_matrix(df_outlier_remove, dimensions=columns[2:], hover_data=['Plot', 'KeyID'],
#                         height=1000, width=1000, title="Scatter Plot Matrix")
# fig.update_traces(showupperhalf=False, diagonal_visible=False)
# fig.show()

,Plot,KeyID,hq85,q75CHT,hvar,hq95,hq75,hsd,MaxCHT,hmax,hq65,SVol,TRV (m3 sub)
70,E063T1A,GLBC019705,16.82300,16.853,58.02,18.12800,16.14600,7.62,19.968,19.97,15.56200,13519.838,77.4
71,E064T1A,GLBC019901,16.33000,16.132,48.69,17.54100,15.39925,6.98,19.548,19.55,14.34500,11632.046,79.3
73,E066T6A,GLBC020004,15.09300,14.963,44.81,16.08390,14.28800,6.69,17.677,17.68,13.34200,10543.639,71.5
74,E067T1A,GLBC020102,16.00080,15.995,43.03,17.12400,14.78400,6.56,19.204,19.20,13.21520,11596.003,66.2
75,E068T15A,GLBC020102,14.52300,14.514,39.25,15.44700,13.66100,6.27,16.785,16.78,12.67800,10607.942,52.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,E292T10A,TPGE068B01,16.76305,16.534,52.93,17.98435,15.88400,7.28,19.750,19.75,14.98545,11588.154,83.6
215,E293T10A,TPGE101A01,18.89100,18.607,70.56,19.94000,18.14500,8.40,22.012,22.01,17.41600,13561.266,120.7
216,E294T13A,TPGE146A01,18.04585,17.858,66.99,18.90800,17.37600,8.19,21.449,21.45,16.72900,13171.349,104.2
217,E295T8B,TPGE146A02,16.99370,16.670,58.69,17.69700,16.32550,7.66,18.841,18.84,15.72600,11562.205,75.4
218,E296T21A,TPGE147A01,18.16000,17.980,69.65,18.92400,17.55500,8.35,20.386,20.39,16.99015,12444.173,98.7

In [7]:
# from sklearn.model_selection import train_test_split, cross_val_score
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import make_pipeline
# from sklearn.linear_model import Lasso, Ridge
# from sklearn.svm import SVR
# from sklearn.neighbors import KNeighborsRegressor
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
# from xgboost import XGBRegressor

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# scaler = StandardScaler()
# model = [Lasso(), Ridge(), SVR(), KNeighborsRegressor(), DecisionTreeRegressor(), 
#          RandomForestRegressor(), AdaBoostRegressor(), GradientBoostingRegressor()]

# for i in range(len(model)):
#     pipe = make_pipeline(scaler, model[i])
#     cv_score = cross_val_score(pipe, X_train, y_train, cv=5, scoring='r2', n_jobs=-1)
#     print(np.mean(cv_score))

In [8]:
!pip install tpot

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tpot
  Downloading TPOT-0.11.7-py3-none-any.whl (87 kB)
     |████████████████████████████████| 87 kB 7.0 MB/s
Collecting deap>=1.2
  Downloading deap-1.3.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (139 kB)
     |████████████████████████████████| 139 kB 74.1 MB/s
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.3.5)
Collecting xgboost>=1.1.0
  Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl (255.9 MB)
     |████████████████████████████████| 255.9 MB 56 kB/s
Collecting stopit>=1.1.1
  Downloading stopit-1.1.2.tar.gz (18 kB)
Requirement already satisfied: numpy>=1.16.3 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.21.6)
Collecting update-checker>=0.16
  Downloading update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.7/dist-packages (from tpot) (4.64.1)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.7.3)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.2.0)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.0.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->tpot) (2022.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->tpot) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.2->tpot) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.22.0->tpot) (3.1.0)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from update-checker>=0.16->tpot) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2.10)
Building wheels for collected packages: stopit
  Building wheel for stopit (setup.py) ... done
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11956 sha256=487762384c54e8762c6eccb9a3cf3acedaa77030813e4b559fe47997ea136b05
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
Installing collected packages: xgboost, update-checker, stopit, deap, tpot
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90
Successfully installed deap-1.3.3 stopit-1.1.2 tpot-0.11.7 update-checker-0.18.0 xgboost-1.6.2

In [14]:
X = df_outlier_remove[feature_interest[2:]]
y = df_outlier_remove[target_interest]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()

In [17]:
import tpot

# X_train2 = scaler.fit_transform(X_train.values)
# y_train2 = scaler.fit_transform(y_train.values.reshape(-1,1))

reg = tpot.TPOTRegressor(n_jobs=-1, verbosity=2, generations=200, warm_start=True, scoring='r2')

In [ ]:
reg.fit(X_train.values, y_train.values.reshape(-1,1))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Optimization Progress:   0%|          | 0/20100 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.6095648729713259

Generation 2 - Current best internal CV score: 0.6095648729713259

Generation 3 - Current best internal CV score: 0.6095648729713259

Generation 4 - Current best internal CV score: 0.6204824847282681

Generation 5 - Current best internal CV score: 0.6207650146112644

Generation 6 - Current best internal CV score: 0.6267499991816126

Generation 7 - Current best internal CV score: 0.6288003751602232

Generation 8 - Current best internal CV score: 0.6311289669208426

Generation 9 - Current best internal CV score: 0.6311289669208426

Generation 10 - Current best internal CV score: 0.6413729439887734

Generation 11 - Current best internal CV score: 0.6413729439887734

Generation 12 - Current best internal CV score: 0.6413729439887734

Generation 13 - Current best internal CV score: 0.6413729439887734

Generation 14 - Current best internal CV score: 0.6413729439887734

Generation 15 - Current best internal CV score: 0.6413729439887734

Generation 16 - Current best internal CV score: 0.6445409530310611

Generation 17 - Current best internal CV score: 0.6445409530310611

Generation 18 - Current best internal CV score: 0.6445409530310611

Generation 19 - Current best internal CV score: 0.6445409530310611

Generation 20 - Current best internal CV score: 0.6445409530310611

Generation 21 - Current best internal CV score: 0.6445409530310611

Generation 22 - Current best internal CV score: 0.6445409530310611

Generation 23 - Current best internal CV score: 0.6445409530310611

Generation 24 - Current best internal CV score: 0.6445409530310611

Generation 25 - Current best internal CV score: 0.6445409530310611

Generation 26 - Current best internal CV score: 0.6445409530310611

Generation 27 - Current best internal CV score: 0.6473569379448558

Generation 28 - Current best internal CV score: 0.6473569379448558

Generation 29 - Current best internal CV score: 0.6483512293293827

Generation 30 - Current best internal CV score: 0.6483512293293827

Generation 31 - Current best internal CV score: 0.6483512293293829

In [ ]:
re.export('/data2/users/yohan/LiDAR/best_pipeline.py')

In [ ]:
plt.figure(figsize=(13,13))
for i in range(len(feature_interest)):
    feature = feature_interest[i]
    plt.subplot(5,4,i+1)
    plt.scatter(df_interest[feature], df_interest[target_interest], s=5)
    plt.xlabel(feature)
    plt.ylabel(target_interest)
plt.tight_layout()